wipe GPG home when keys change
drGrove/mtls-server pull request #55
Opened 2021-12-02 14:15 UTC by jimethn

mtls-server is locked down read-only, and so requires a volume mounted at the configured GPG home. This patch mounts an emptyDir there, but expands the restart script to wipe it so that keys removed from the seed dir are also removed from the keychain.

The second commit fixes a bug in `mtls-server.sync` where the seed data was being read as a string rather than binary.

2021-12-02 19:16 UTC, drGrove requested changes

2021-12-02 19:16 UTC, drGrove commented on mtls_server/sync.py
> +                            with open(f_path, "rb") as key_file:
PGP files can be either binary or ASCII armoured. We should probably support both here.

2021-12-03 14:26 UTC, jimethn commented on mtls_server/sync.py
> +                            with open(f_path, "rb") as key_file:
good call, I guess that makes this more of a feature. updated.

2021-12-14 06:36 UTC, drGrove approved these changes

2021-12-14 06:36 UTC, merged